{{- if .Values.deployments.directUpload.enabled }}
{{- $context := (dict
      "dot" .
      "component" "deployments"
      "containerName" "deployments-storage-daemon"
      "override" .Values.deployments
      "args" (printf "storage-daemon --time-jitter=%q"
            .Values.deployments.directUpload.jitter )
) -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "mender.fullname" . }}-deployments-storage-daemon
  namespace: {{ .Release.Namespace }}
spec:
  schedule: {{default "15 * * * *" .Values.deployments.daemonSchedule | quote}}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        {{- include "mender.deploymentsPodTemplate" $context | nindent 8 }}
{{- end -}}
