{{- if and .Values.deployments.enabled .Values.dbmigration.enable }}
{{- $context := (dict
      "dot" .
      "containerName" "deployments-migration"
      "component" "deployments"
      "override" .Values.deployments
      "restartPolicy" (default "Never" .Values.deployments.migrationRestartPolicy)
      "resources" .Values.deployments.migrationResources
      "migration" "true") -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mender.servicename" $context }}-migration
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "mender.labels" $context | nindent 4 }}
spec:
  backoffLimit: 5
  template:
    {{- include "mender.deploymentsPodTemplate" $context | nindent 4}}

{{- end }}
