apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: devauth
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: mender
    helm.sh/chart: "{{ .Chart.Name }}"
spec:
  forwardAuth:
    address: "http://{{ .Values.device_auth.service.name }}:{{ .Values.device_auth.service.port }}/api/internal/v1/devauth/tokens/verify"
    authResponseHeaders:
      - X-MEN-RequestID
