apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: inventory-v1-repl-devices
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: mender
    helm.sh/chart: "{{ .Chart.Name }}"
spec:
  redirectRegex:
    regex: "^/api/devices/v1/inventory/(.*)"
    replacement: "/api/0.1.0/attributes"
