apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: secure-headers
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: mender
    helm.sh/chart: "{{ .Chart.Name }}"
spec:
  headers:
    referrerPolicy: "no-referrer"
    stsSeconds: 31536000
    forceSTSHeader: true
    stsPreload: true
    stsIncludeSubdomains: true
    browserXssFilter: true
    customRequestHeaders:
      X-Forwarded-Proto: {{ ternary "https" "http" (.Values.api_gateway.env.SSL)}}
