auditlogs:
  image:
    tag: staging_a3d45bf02b189dce509872419b5266e77c53d526
    registry: registry.mender.io
    repository: mendersoftware/auditlogs
deployments:
  image:
    tag: staging_7f657a7cd969321065ffd1668bf7ee1f05bedb48
    registry: registry.mender.io
    repository: mendersoftware/deployments-enterprise
inventory:
  image:
    tag: staging_9d40c2aa753181815cc9c514e0a70818ded69e6f
    registry: registry.mender.io
    repository: mendersoftware/inventory-enterprise
create_artifact_worker:
  image:
    tag: staging_6cda58cf8649b202774ecaf53f89452e51899cd1
    registry: mendersoftware
    repository: create-artifact-worker
generate_delta_worker:
  image:
    tag: staging_7ff438dedd1569c7c9ae79d421d0343181d4e992
    registry: registry.mender.io
    repository: mendersoftware/generate-delta-worker
deviceconnect:
  image:
    tag: staging_b6d5272b45c620cdb28c4462f4f1ee873866f1c0
    registry: mendersoftware
    repository: deviceconnect
device_auth:
  image:
    tag: staging_19ab87cf5ec5cf18380a961f184ccff2611c88cc
    registry: registry.mender.io
    repository: mendersoftware/deviceauth-enterprise
tenantadm:
  image:
    tag: staging_f1d24358f9c69ca8150b4b246d4f7ce1c59afe6b
    registry: registry.mender.io
    repository: mendersoftware/tenantadm
devicemonitor:
  image:
    tag: staging_8d2aacda036f936445d6bc4ab39537f43a019886
    registry: registry.mender.io
    repository: mendersoftware/devicemonitor
useradm:
  image:
    tag: staging_3b6f36f74164b591e220b4adf7c929bc7dc1d608
    registry: registry.mender.io
    repository: mendersoftware/useradm-enterprise
