auditlogs:
  image:
    tag: staging_a3d45bf02b189dce509872419b5266e77c53d526
    registry: registry.mender.io
    repository: mendersoftware/auditlogs
deployments:
  image:
    tag: staging_7aa8ef96a00d596b3b8cdbc40e365b93d3c0b423
    registry: registry.mender.io
    repository: mendersoftware/deployments-enterprise
