useradm:
  image:
    tag: saas-v2024.04.26
    registry: registry.mender.io
    repository: mendersoftware/useradm-enterprise
generate_delta_worker:
  image:
    tag: saas-v2024.04.29
    registry: registry.mender.io
    repository: mendersoftware/generate-delta-worker
auditlogs:
  image:
    tag: saas-v2024.04.29
    registry: registry.mender.io
    repository: mendersoftware/auditlogs
device_auth:
  image:
    tag: saas-v2024.04.29
    registry: registry.mender.io
    repository: mendersoftware/deviceauth-enterprise
deviceconfig:
  image:
    tag: saas-v2024.04.29
    registry: mendersoftware
    repository: deviceconfig
create_artifact_worker:
  image:
    tag: saas-v2024.04.29
    registry: mendersoftware
    repository: create-artifact-worker
