auditlogs:
  image:
    tag: staging_cdc2e6436d761f0cc425289ffdb9154fbd0bb9cd
    registry: registry.mender.io
    repository: mendersoftware/auditlogs
deployments:
  image:
    tag: staging_46d39edf078c7ed6f217d4303cd7fa1e74a1f2a6
    registry: registry.mender.io
    repository: mendersoftware/deployments-enterprise
inventory:
  image:
    tag: staging_75eb90923c0219472907a441193e51b7cf870c16
    registry: registry.mender.io
    repository: mendersoftware/inventory-enterprise
create_artifact_worker:
  image:
    tag: staging_d707e6f254da69cb3139d76aaf6e4f1e79462f7d
    registry: mendersoftware
    repository: create-artifact-worker
generate_delta_worker:
  image:
    tag: staging_ba1010d82fdb1f8420fd36ab2dc76252028f139a
    registry: registry.mender.io
    repository: mendersoftware/generate-delta-worker
deviceconnect:
  image:
    tag: staging_d6de4e76483e2ca75842ca1c82632cb88c631d80
    registry: mendersoftware
    repository: deviceconnect
device_auth:
  image:
    tag: staging_fe55ad17d11f98790a9afc9c52cc19c93c5b7c08
    registry: registry.mender.io
    repository: mendersoftware/deviceauth-enterprise
tenantadm:
  image:
    tag: staging_95fe06cdb6c69da3f6eeb0b2aaa336ca04772da1
    registry: registry.mender.io
    repository: mendersoftware/tenantadm
devicemonitor:
  image:
    tag: staging_8053b908ff936aa9c065c47221ddbbd83738d57e
    registry: registry.mender.io
    repository: mendersoftware/devicemonitor
useradm:
  image:
    tag: staging_51da64eb83c15fbd1a6c006ff68991a308082cc5
    registry: registry.mender.io
    repository: mendersoftware/useradm-enterprise
deviceconfig:
  image:
    tag: staging_fd4d1435b41c3554f09f33558e1909f54d7a0a24
    registry: mendersoftware
    repository: deviceconfig
iot_manager:
  image:
    tag: staging_dbb4c171b78d8508086e5c90bf2649f33f23c930
    registry: mendersoftware
    repository: iot-manager
workflows:
  image:
    tag: staging_e1d6dda2b51c8ad3824183266720077a6a0507ec
    registry: registry.mender.io
    repository: mendersoftware/workflows-enterprise
gui:
  image:
    tag: staging_97d697ed056d66ec75039728a1060fa1154e859e
    registry: mendersoftware
    repository: gui
