auditlogs:
  image:
    tag: staging_a3d45bf02b189dce509872419b5266e77c53d526
    registry: registry.mender.io
    repository: mendersoftware/auditlogs
deployments:
  image:
    tag: staging_288aa0be69488aa11143b4e50aa5883c2cd4efc4
    registry: registry.mender.io
    repository: mendersoftware/deployments-enterprise
