useradm:
  image:
    tag: saas-v2024.04.26
    registry: registry.mender.io
    repository: mendersoftware/useradm-enterprise
generate_delta_worker:
  image:
    tag: saas-v2024.04.29
    registry: registry.mender.io
    repository: mendersoftware/generate-delta-worker
