auditlogs:
  image:
    tag: staging_8fafacdbc9762979a590a2fe580899f1b9dda5b4
    registry: registry.mender.io
    repository: mendersoftware/auditlogs
deployments:
  image:
    tag: staging_58f24e0345cc2504a53aabd8b6650edf6a81875b
    registry: registry.mender.io
    repository: mendersoftware/deployments-enterprise
inventory:
  image:
    tag: staging_e3e924b021131b9d8f473933b903fad81725cbc9
    registry: registry.mender.io
    repository: mendersoftware/inventory-enterprise
create_artifact_worker:
  image:
    tag: staging_7bdd1b5b6b899addfc39bb21015656333734f576
    registry: mendersoftware
    repository: create-artifact-worker
generate_delta_worker:
  image:
    tag: staging_23ae8454267be41e3c28fbc079e6b1a38ff722f9
    registry: registry.mender.io
    repository: mendersoftware/generate-delta-worker
deviceconnect:
  image:
    tag: staging_77dc22554720d18b743ad87e92b94755fc0f0d75
    registry: mendersoftware
    repository: deviceconnect
device_auth:
  image:
    tag: staging_35c8db966f0c8dfd2f88a7f1b89686730abfe942
    registry: registry.mender.io
    repository: mendersoftware/deviceauth-enterprise
tenantadm:
  image:
    tag: staging_fe23b056bd8d7a56f4bc1daf437c611cee9ae370
    registry: registry.mender.io
    repository: mendersoftware/tenantadm
devicemonitor:
  image:
    tag: staging_a43b62134d9538fd98e6f7c7044f9109eef93822
    registry: registry.mender.io
    repository: mendersoftware/devicemonitor
useradm:
  image:
    tag: staging_9e10ae611edff48a1783c5ae0f483c8d35e36b62
    registry: registry.mender.io
    repository: mendersoftware/useradm-enterprise
deviceconfig:
  image:
    tag: staging_630719591b75ae642b822e9221161213b713ec77
    registry: mendersoftware
    repository: deviceconfig
iot_manager:
  image:
    tag: staging_45d5eec5ea9703edce3ef26bee1426eab730d36c
    registry: mendersoftware
    repository: iot-manager
workflows:
  image:
    tag: staging_9b8a9b980291fb788e0c18edf779c464e6f95dab
    registry: registry.mender.io
    repository: mendersoftware/workflows-enterprise
gui:
  image:
    tag: staging_ac3cef9f17f307e2a7948658544e5a32d6b34fb8
    registry: mendersoftware
    repository: gui
