auditlogs:
  image:
    tag: staging_a3d45bf02b189dce509872419b5266e77c53d526
    registry: registry.mender.io
    repository: mendersoftware/auditlogs
deployments:
  image:
    tag: staging_126bcdebb5ed92348289012c964fcd1ecd9553b2
    registry: registry.mender.io
    repository: mendersoftware/deployments-enterprise
